# Generated by Django 2.2.1 on 2019-06-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('metadata_endpoint', models.URLField()),
                ('creator', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('version', models.IntegerField()),
                ('data_endpoint', models.URLField()),
                ('metadata_endpoint', models.URLField()),
                ('rating', models.CharField(choices=[('OP', 'Open'), ('CU', 'Curated'), ('BL', 'Blocked')], default='OP', max_length=2)),
                ('visualization_type', models.CharField(choices=[('SM', 'ScatterPlotMap'), ('TX', 'Text'), ('CM', 'ChoroplethMap')], default='SM', max_length=2)),
                ('creator', models.CharField(max_length=50)),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Package')),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
        ),
    ]
