# Generated by Django 2.2.4 on 2019-08-22 23:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [        
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('data_endpoint', models.URLField()),
                ('metadata_endpoint', models.URLField()),
                ('rating', models.CharField(choices=[('UN', 'UN'), ('OP', 'Open'), ('CU', 'Curated'), ('BL', 'Blocked')], default='UN', max_length=2)),
                ('visualization_type', models.CharField(choices=[('UN', 'UN'), ('PM', 'Path Map'), ('IM', 'Icon Map'), ('SP', 'Small Polygon Map'), ('SM', 'ScatterPlot Map'), ('TX', 'Text'), ('CM', 'Choropleth Map')], default='UN', max_length=2)),
                ('creator', models.CharField(max_length=50)),
                ('aggregation', models.CharField(choices=[('UN', 'UN'), ('AG', 'Aggregatable'), ('AB', 'Aggregate By'), ('PA', 'Pre-Aggregated'), ('NO', 'None')], default='NO', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('metadata_endpoint', models.URLField()),
                ('created', models.DateTimeField(null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('contributor', models.CharField(max_length=50, null=True)),
                ('curation', models.CharField(choices=[('UN', 'UN'), ('CC', 'Civic Curated'), ('CE', 'Civic Endorsed'), ('CA', 'Contributor Assembled'), ('UA', 'User Assembled')], default='UN', max_length=2)),
                ('affiliation', models.CharField(max_length=50)),
                ('layers', models.ManyToManyField(to='api.Layer')),
                ('tags', models.ManyToManyField(to='api.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='tags',
            field=models.ManyToManyField(to='api.Tag'),
        ),
    ]
