FROM hackoregoncivic/backend-docker-django
MAINTAINER Brian H. Grant <brian@hackoregon.org> & "M. Edward (Ed) Borasky <ed.borasky@hackoregon.org>
ENV PYTHONUNBUFFERED 1
ARG DEBUG=false

WORKDIR /code

COPY /requirements/* /code/
COPY hackoregon_sandbox /code/hackoregon_sandbox
COPY local_settings /code/local_settings

RUN if [ "$DEBUG" = true  ] ; then pip install -r development.txt ; else pip install -r production.txt ; fi

RUN python

RUN mkdir src_files
COPY bin /code/src_files/bin/
COPY local_settings /code/src_files/local_settings

RUN chmod +x *.py

ENTRYPOINT [ "/code/src_files/bin/docker-entrypoint.sh" ]
