version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: DOCKERFILE
    image: api
    command: ./scripts/build-run/docker-entrypoint.sh
    #expose: 
    #  - 8000
    volumes:
      - .:/code/src_files/
      # - ./hackoregon_sandbox/api:/code/src_files/hackoregon_sandbox/api      
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}

  nginx:
    build:
      context: ./nginx
      dockerfile: DOCKERFILE
    ports:
      - 80:80
    depends_on:
      - api
